# Author: Jace
# This ansible role will install go v1.10 and remove older version.
# 

---
- name: Set bootstrap_os
  set_fact:
    os_family: >-
      {%- if 'Ubuntu' in os_release.stdout -%}
      ubuntu
      {%- elif 'Debian' in os_release.stdout -%}
      debian
      {%- elif 'CoreOS' in os_release.stdout -%}
      coreos
      {%- elif 'Fedora' in os_release.stdout -%}
      fedora
      {%- elif 'CentOS' in os_release.stdout -%}
      centos
      {%- elif 'OpenSUSE' in os_release.stdout -%}
      opensuse
      {%- endif -%}

- include_tasks: go-ubuntu.yml
  when: os_family == "ubuntu"

- include_tasks: go-debian.yml
  when: os_family == "debian"

